/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El proceso esta vivo */
        get: operations["SaludController_vivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/salud/listo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El servicio y sus dependencias responden */
        get: operations["SaludController_listo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inicia sesion
         * @description Devuelve los tokens, o mfaRequerido=true con un token parcial si el rol exige segundo factor.
         */
        post: operations["AutenticacionController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/mfa/verificar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Completa el login con el codigo de segundo factor */
        post: operations["AutenticacionController_verificarMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refrescar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rota el token de refresco y emite uno de acceso nuevo */
        post: operations["AutenticacionController_refrescar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/cerrar-sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoca la sesion indicada */
        post: operations["AutenticacionController_cerrarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/mfa/configurar-inicial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Configura el segundo factor por primera vez, sin sesion previa
         * @description Para cuentas cuyo rol exige MFA y que aun no lo configuraron. Se autoriza con el token parcial del login, no con un token de acceso: sin esto la cuenta inicial del sistema no podria entrar nunca. Devuelve el QR, el secreto y los codigos de respaldo. El segundo factor queda INACTIVO hasta confirmarlo en mfa/activar-inicial.
         */
        post: operations["AutenticacionController_configurarMfaInicial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/mfa/activar-inicial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirma la primera configuracion y abre la sesion
         * @description Devuelve los tokens directamente: a estas alturas la persona ya demostro contrasena correcta y control de su aplicacion de autenticacion.
         */
        post: operations["AutenticacionController_activarMfaInicial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/yo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil del usuario autenticado */
        get: operations["AutenticacionController_yo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/contrasena": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cambia la propia contrasena */
        post: operations["AutenticacionController_cambiarContrasena"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/mfa/configurar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Genera el secreto TOTP y los codigos de respaldo
         * @description El segundo factor queda INACTIVO hasta confirmarlo en mfa/activar.
         */
        post: operations["AutenticacionController_configurarMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/mfa/activar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirma con un codigo real y activa el segundo factor */
        post: operations["AutenticacionController_activarMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista paginada de cuentas */
        get: operations["UsuariosController_listar"];
        put?: never;
        /**
         * Crea una cuenta
         * @description Devuelve una contrasena temporal. Es la unica vez que se muestra: anotela y entreguela a la persona.
         */
        post: operations["UsuariosController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usuarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene una cuenta por su identificador */
        get: operations["UsuariosController_obtener"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualiza datos, rol o estado de una cuenta */
        patch: operations["UsuariosController_actualizar"];
        trace?: never;
    };
    "/v1/usuarios/{id}/reiniciar-mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Borra el segundo factor para que la persona lo configure de nuevo
         * @description Para quien perdio el telefono con la aplicacion de autenticacion. Borra tambien sus codigos de respaldo y cierra sus sesiones. No devuelve ningun secreto: el nuevo lo genera la propia persona al entrar.
         */
        post: operations["UsuariosController_reiniciarMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usuarios/{id}/restablecer-contrasena": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Genera una contrasena temporal nueva y cierra las sesiones */
        post: operations["UsuariosController_restablecer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SaludVivoDto: {
            /**
             * @example vivo
             * @enum {string}
             */
            estado: "vivo";
            /** Format: date-time */
            fecha: string;
        };
        SaludListoDto: {
            /**
             * @example listo
             * @enum {string}
             */
            estado: "listo";
            /**
             * @description 'ok' cuando la base responde. Si no, el endpoint devuelve 503 en vez de este cuerpo.
             * @example ok
             */
            baseDatos: string;
        };
        /** @enum {string} */
        Rol: "ADMINISTRADOR" | "DIRECTOR" | "MEDICO" | "ENFERMERIA" | "FARMACIA" | "RECEPCION";
        PerfilDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Nombre de usuario, siempre en minusculas.
             * @example jlopez
             */
            usuario: string;
            rol: components["schemas"]["Rol"];
            /**
             * @description Si es true, el panel debe obligar al cambio antes de dejar trabajar.
             * @example false
             */
            debeCambiarContrasena: boolean;
        };
        SesionAbiertaDto: {
            /**
             * @description Discriminante: false significa que ya hay sesion.
             * @enum {boolean}
             */
            mfaRequerido: false;
            /** @description JWT de acceso. Vida corta; se renueva con el token de refresco. */
            tokenAcceso: string;
            /** @description Token de refresco rotatorio. Reutilizarlo revoca toda la sesion. */
            tokenRefresco: string;
            usuario: components["schemas"]["PerfilDto"];
        };
        MfaRequeridoDto: {
            /**
             * @description Discriminante: true significa que falta el segundo factor.
             * @enum {boolean}
             */
            mfaRequerido: true;
            /** @description true cuando la cuenta aun no ha configurado el TOTP y debe hacerlo ahora. */
            configuracionPendiente: boolean;
            /** @description Token de un solo uso para completar el login. No es un token de acceso. */
            tokenParcial: string;
        };
        LoginDto: {
            /** @example jperez */
            usuario: string;
            /** @example Clave-Del-Personal-2026 */
            contrasena: string;
        };
        VerificarMfaDto: {
            /** @description Token parcial devuelto por el login */
            tokenParcial: string;
            /**
             * @description Codigo TOTP de 6 digitos o codigo de respaldo
             * @example 123456
             */
            codigo: string;
        };
        RefrescarDto: {
            tokenRefresco: string;
        };
        RefrescoDto: {
            tokenAcceso: string;
            tokenRefresco: string;
            usuario: components["schemas"]["PerfilDto"];
        };
        ConfigurarMfaInicialDto: {
            /** @description Token parcial devuelto por el login */
            tokenParcial: string;
        };
        ConfiguracionMfaDto: {
            /**
             * @description URI otpauth. El panel la convierte en codigo QR para la app de autenticacion.
             * @example otpauth://totp/CAP%20Purulha:jlopez?secret=...
             */
            uri: string;
            /** @description El mismo secreto en texto, por si hay que escribirlo a mano. */
            secreto: string;
            /** @description Codigos de un solo uso. Es la UNICA vez que se muestran en claro. */
            codigosRespaldo: string[];
        };
        PerfilPropioDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Nombre de usuario, siempre en minusculas.
             * @example jlopez
             */
            usuario: string;
            rol: components["schemas"]["Rol"];
            /**
             * @description Si es true, el panel debe obligar al cambio antes de dejar trabajar.
             * @example false
             */
            debeCambiarContrasena: boolean;
            /** @description Segundo factor ya confirmado y en uso. */
            mfaActivo: boolean;
        };
        CambiarContrasenaDto: {
            contrasenaActual: string;
            contrasenaNueva: string;
        };
        ActivarMfaDto: {
            /**
             * @description Los seis digitos de la aplicacion.
             * @example 123456
             */
            codigo: string;
        };
        PaginaDto: {
            /**
             * @description Pagina devuelta, empezando en 1.
             * @example 1
             */
            pagina: number;
            /**
             * @description Registros por pagina. El servidor recorta cualquier valor mayor al maximo.
             * @example 25
             */
            tamano: number;
            /**
             * @description Total de registros que cumplen el filtro.
             * @example 137
             */
            total: number;
            /**
             * @description Total de paginas. Nunca es menor que 1.
             * @example 6
             */
            totalPaginas: number;
        };
        CuentaDto: {
            /** Format: uuid */
            id: string;
            /** @example jlopez */
            usuario: string;
            /** @example Juana */
            nombres: string;
            /** @example Lopez Chub */
            apellidos: string;
            rol: components["schemas"]["Rol"];
            /** @description Una cuenta desactivada no puede iniciar sesion. */
            activo: boolean;
            debeCambiarContrasena: boolean;
            /** @description true si el segundo factor esta configurado y activo. Nunca se expone el secreto. */
            mfaActivo: boolean;
            /** @description true si la cuenta esta bloqueada AHORA por intentos fallidos. */
            bloqueada: boolean;
            /**
             * Format: date-time
             * @description Hasta cuando dura el bloqueo. Puede ser una fecha ya pasada.
             */
            bloqueadoHasta: string | null;
            /**
             * Format: date-time
             * @description null si la cuenta nunca ha entrado.
             */
            ultimoAcceso: string | null;
            /** Format: date-time */
            creadoEn: string;
        };
        CrearUsuarioDto: {
            /** @example jperez */
            usuario: string;
            /** @example Juana */
            nombres: string;
            /** @example Perez Caal */
            apellidos: string;
            /** @enum {string} */
            rol: "ADMINISTRADOR" | "DIRECTOR" | "MEDICO" | "ENFERMERIA" | "FARMACIA" | "RECEPCION";
        };
        CuentaCreadaDto: {
            /** Format: uuid */
            id: string;
            /** @example jlopez */
            usuario: string;
            /** @example Juana */
            nombres: string;
            /** @example Lopez Chub */
            apellidos: string;
            rol: components["schemas"]["Rol"];
            /** @description Una cuenta desactivada no puede iniciar sesion. */
            activo: boolean;
            debeCambiarContrasena: boolean;
            /** @description true si el segundo factor esta configurado y activo. Nunca se expone el secreto. */
            mfaActivo: boolean;
            /** @description true si la cuenta esta bloqueada AHORA por intentos fallidos. */
            bloqueada: boolean;
            /**
             * Format: date-time
             * @description Hasta cuando dura el bloqueo. Puede ser una fecha ya pasada.
             */
            bloqueadoHasta: string | null;
            /**
             * Format: date-time
             * @description null si la cuenta nunca ha entrado.
             */
            ultimoAcceso: string | null;
            /** Format: date-time */
            creadoEn: string;
            /** @description Anotela y entreguela a la persona. No se puede volver a consultar. */
            contrasenaTemporal: string;
        };
        ActualizarUsuarioDto: {
            nombres?: string;
            apellidos?: string;
            /** @enum {string} */
            rol?: "ADMINISTRADOR" | "DIRECTOR" | "MEDICO" | "ENFERMERIA" | "FARMACIA" | "RECEPCION";
            activo?: boolean;
        };
        MfaReiniciadoDto: {
            /** @description Cuenta a la que se le reinicio el segundo factor. */
            usuario: string;
            /** @description true si su rol lo exige: el sistema se lo volvera a pedir al entrar. Si es false, entrara sin el hasta que decida configurarlo. */
            exigeSegundoFactor: boolean;
        };
        ContrasenaRestablecidaDto: {
            /** @description Nombre de usuario al que corresponde la contrasena nueva. */
            usuario: string;
            /** @description Temporal: la persona debera cambiarla al entrar. */
            contrasenaTemporal: string;
        };
        RespuestaErrorDto: {
            /**
             * @description Codigo estable. El cliente decide que hacer segun este valor, no segun el mensaje.
             * @example VALIDACION
             * @enum {string}
             */
            codigo: "VALIDACION" | "NO_AUTENTICADO" | "SIN_PERMISO" | "NO_ENCONTRADO" | "CONFLICTO" | "DEMASIADAS_PETICIONES" | "ERROR_INTERNO";
            /**
             * @description Mensaje en espanol, apto para mostrarse tal cual al usuario.
             * @example La informacion enviada no es valida.
             */
            mensaje: string;
            /**
             * @description Detalle por campo. Presente sobre todo en errores de validacion.
             * @example [
             *       "dpi debe tener 13 digitos"
             *     ]
             */
            detalles?: string[];
            /**
             * @description Identificador de correlacion. Es lo que se busca en los logs para esta peticion.
             * @example 7f3a1c2e-9b4d-4e21-8a55-0c1d2e3f4a5b
             */
            trazaId: string;
            /** @example /v1/pacientes */
            ruta: string;
            /**
             * Format: date-time
             * @example 2026-08-26T15:04:05.000Z
             */
            fecha: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    SaludController_vivo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludVivoDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    SaludController_listo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludListoDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description La base de datos no responde. El gateway debe dejar de enviar trafico a esta instancia. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AutenticacionController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Sesion abierta, o segundo factor pendiente. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionAbiertaDto"] | components["schemas"]["MfaRequeridoDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    AutenticacionController_verificarMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificarMfaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionAbiertaDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    AutenticacionController_refrescar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefrescarDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefrescoDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    AutenticacionController_cerrarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefrescarDto"];
            };
        };
        responses: {
            /** @description Sesion revocada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    AutenticacionController_configurarMfaInicial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigurarMfaInicialDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfiguracionMfaDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description La cuenta ya tiene el segundo factor configurado. Use mfa/verificar. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    AutenticacionController_activarMfaInicial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificarMfaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionAbiertaDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description La cuenta ya tiene el segundo factor configurado. Use mfa/verificar. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    AutenticacionController_yo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PerfilPropioDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    AutenticacionController_cambiarContrasena: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambiarContrasenaDto"];
            };
        };
        responses: {
            /** @description Contrasena actualizada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    AutenticacionController_configurarMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfiguracionMfaDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    AutenticacionController_activarMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivarMfaDto"];
            };
        };
        responses: {
            /** @description Segundo factor activado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    UsuariosController_listar: {
        parameters: {
            query?: {
                pagina?: number;
                tamano?: number;
                rol?: "ADMINISTRADOR" | "DIRECTOR" | "MEDICO" | "ENFERMERIA" | "FARMACIA" | "RECEPCION";
                /** @description Busca en usuario, nombres y apellidos */
                buscar?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["CuentaDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    UsuariosController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearUsuarioDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CuentaCreadaDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    UsuariosController_obtener: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CuentaDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    UsuariosController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarUsuarioDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CuentaDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    UsuariosController_reiniciarMfa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaReiniciadoDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    UsuariosController_restablecer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContrasenaRestablecidaDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
}
