/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El proceso esta vivo */
        get: operations["SaludController_vivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/salud/listo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El servicio y sus dependencias responden */
        get: operations["SaludController_listo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/medicamentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogo con la existencia total de cada medicamento */
        get: operations["CatalogoController_listar"];
        put?: never;
        /** Da de alta un medicamento en el catalogo */
        post: operations["CatalogoController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/medicamentos/bajo-minimo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Medicamentos por debajo de su existencia minima
         * @description Sin paginar: son cientos, no miles. Un minimo en cero desactiva la alerta.
         */
        get: operations["CatalogoController_bajoMinimo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/medicamentos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle con sus lotes y el estado de vencimiento de cada uno */
        get: operations["CatalogoController_obtener"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ajusta existencia minima, receta obligatoria o estado */
        patch: operations["CatalogoController_actualizar"];
        trace?: never;
    };
    "/v1/medicamentos/{medicamentoId}/lotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingresa un lote al inventario */
        post: operations["LotesController_ingresar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lotes/por-vencer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lotes que vencen dentro de la ventana de alerta
         * @description Por defecto usa DIAS_ALERTA_VENCIMIENTO (90 dias).
         */
        get: operations["LotesController_porVencer"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lotes/vencidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lotes vencidos que aun figuran con existencia
         * @description El sistema no los da de baja solo: esa decision necesita un responsable.
         */
        get: operations["LotesController_vencidos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lotes/{id}/baja": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Da de baja lo que queda de un lote */
        patch: operations["LotesController_darDeBaja"];
        trace?: never;
    };
    "/v1/entregas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historial de entregas */
        get: operations["EntregasController_listar"];
        put?: never;
        /**
         * Registra una entrega a un paciente
         * @description El sistema elige los lotes por FEFO (primero el que vence antes). Si algun medicamento no alcanza, NO se entrega nada.
         */
        post: operations["EntregasController_registrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entregas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una entrega */
        get: operations["EntregasController_obtener"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inventario/movimientos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Movimientos de inventario, lo mas reciente primero */
        get: operations["InventarioController_movimientos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SaludVivoDto: {
            /**
             * @example vivo
             * @enum {string}
             */
            estado: "vivo";
            /** Format: date-time */
            fecha: string;
        };
        SaludListoDto: {
            /**
             * @example listo
             * @enum {string}
             */
            estado: "listo";
            /**
             * @description 'ok' cuando la base responde. Si no, el endpoint devuelve 503 en vez de este cuerpo.
             * @example ok
             */
            baseDatos: string;
        };
        PaginaDto: {
            /**
             * @description Pagina devuelta, empezando en 1.
             * @example 1
             */
            pagina: number;
            /**
             * @description Registros por pagina. El servidor recorta cualquier valor mayor al maximo.
             * @example 25
             */
            tamano: number;
            /**
             * @description Total de registros que cumplen el filtro.
             * @example 137
             */
            total: number;
            /**
             * @description Total de paginas. Nunca es menor que 1.
             * @example 6
             */
            totalPaginas: number;
        };
        MedicamentoConExistenciaDto: {
            /** Format: uuid */
            id: string;
            /** @example AMOX500 */
            codigo: string;
            nombreGenerico: string;
            nombreComercial: string | null;
            presentacion: string | null;
            concentracion: string | null;
            /** @enum {string} */
            unidad: "TABLETA" | "CAPSULA" | "JARABE_ML" | "AMPOLLA" | "FRASCO" | "SOBRE" | "UNIDAD" | "GRAMO";
            requiereReceta: boolean;
            activo: boolean;
            /** @example 50 */
            stockMinimo: number;
            /**
             * @description Suma de los lotes DISPONIBLES.
             * @example 320
             */
            existencia: number;
            /** @description false cuando el minimo es cero: la alerta esta desactivada. */
            bajoMinimo: boolean;
        };
        MedicamentoBajoMinimoDto: {
            /** Format: uuid */
            id: string;
            /** @example AMOX500 */
            codigo: string;
            nombreGenerico: string;
            /** @enum {string} */
            unidad: "TABLETA" | "CAPSULA" | "JARABE_ML" | "AMPOLLA" | "FRASCO" | "SOBRE" | "UNIDAD" | "GRAMO";
            /** @example 50 */
            stockMinimo: number;
            /** @example 12 */
            existencia: number;
        };
        LoteDelMedicamentoDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Numero impreso en la caja por el fabricante.
             * @example L-4471
             */
            numeroLote: string;
            /** Format: date-time */
            fechaVencimiento: string;
            /** @example 120 */
            cantidadDisponible: number;
            /** @enum {string} */
            estado: "DISPONIBLE" | "AGOTADO" | "VENCIDO" | "DADO_DE_BAJA";
            /**
             * @description Calculado contra el dia de hoy en Purulha y la ventana de alerta configurada.
             * @enum {string}
             */
            vencimiento: "VIGENTE" | "POR_VENCER" | "VENCIDO";
        };
        MedicamentoDetalleDto: {
            /** Format: uuid */
            id: string;
            /** @example AMOX500 */
            codigo: string;
            nombreGenerico: string;
            nombreComercial: string | null;
            presentacion: string | null;
            concentracion: string | null;
            /** @enum {string} */
            unidad: "TABLETA" | "CAPSULA" | "JARABE_ML" | "AMPOLLA" | "FRASCO" | "SOBRE" | "UNIDAD" | "GRAMO";
            requiereReceta: boolean;
            activo: boolean;
            /** @example 50 */
            stockMinimo: number;
            /**
             * @description Suma de los lotes DISPONIBLES.
             * @example 320
             */
            existencia: number;
            /** @description false cuando el minimo es cero: la alerta esta desactivada. */
            bajoMinimo: boolean;
            /** @description Ordenados por vencimiento: primero el que vence antes. */
            lotes: components["schemas"]["LoteDelMedicamentoDto"][];
        };
        CrearMedicamentoDto: {
            /** @example MED-0142 */
            codigo: string;
            /** @example Amoxicilina */
            nombreGenerico: string;
            /** @example Amoxil */
            nombreComercial?: string;
            /** @example Caja de 100 tabletas */
            presentacion?: string;
            /** @example 500 mg */
            concentracion?: string;
            /** @enum {string} */
            unidad: "TABLETA" | "CAPSULA" | "JARABE_ML" | "AMPOLLA" | "FRASCO" | "SOBRE" | "UNIDAD" | "GRAMO";
            /**
             * @description Debajo de esta existencia total aparece en la alerta. Cero desactiva la alerta.
             * @default 0
             */
            stockMinimo: number;
            /** @default false */
            requiereReceta: boolean;
        };
        MedicamentoDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Codigo interno del CAP, siempre en mayusculas.
             * @example AMOX500
             */
            codigo: string;
            /** @example Amoxicilina */
            nombreGenerico: string;
            nombreComercial: string | null;
            /** @example Caja de 20 */
            presentacion: string | null;
            /** @example 500 mg */
            concentracion: string | null;
            /** @enum {string} */
            unidad: "TABLETA" | "CAPSULA" | "JARABE_ML" | "AMPOLLA" | "FRASCO" | "SOBRE" | "UNIDAD" | "GRAMO";
            /**
             * @description Un minimo en CERO desactiva la alerta de existencia.
             * @example 50
             */
            stockMinimo: number;
            requiereReceta: boolean;
            activo: boolean;
            /** Format: date-time */
            creadoEn: string;
            /** Format: date-time */
            actualizadoEn: string;
        };
        IngresarLoteDto: {
            /**
             * @description Numero impreso en la caja
             * @example L-2026-0871
             */
            numeroLote: string;
            /**
             * Format: date-time
             * @example 2027-08-31
             */
            fechaVencimiento: string;
            /** @example 500 */
            cantidad: number;
            /** @example Almacen departamental MSPAS */
            proveedor?: string;
        };
        LoteDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            medicamentoId: string;
            /** @example L-4471 */
            numeroLote: string;
            /** Format: date-time */
            fechaVencimiento: string;
            /** Format: date-time */
            fechaIngreso: string;
            proveedor: string | null;
            /** @example 500 */
            cantidadInicial: number;
            /**
             * @description Existencia actual. Desnormalizada a proposito; el libro mayor la explica.
             * @example 320
             */
            cantidadDisponible: number;
            /** @enum {string} */
            estado: "DISPONIBLE" | "AGOTADO" | "VENCIDO" | "DADO_DE_BAJA";
            motivoBaja: string | null;
            /** Format: date-time */
            creadoEn: string;
        };
        MedicamentoDelLoteDto: {
            /** @example AMOX500 */
            codigo: string;
            nombreGenerico: string;
            /** @enum {string} */
            unidad: "TABLETA" | "CAPSULA" | "JARABE_ML" | "AMPOLLA" | "FRASCO" | "SOBRE" | "UNIDAD" | "GRAMO";
        };
        LotePorVencerDto: {
            /** Format: uuid */
            id: string;
            /** @example L-4471 */
            numeroLote: string;
            medicamento: components["schemas"]["MedicamentoDelLoteDto"];
            /** Format: date-time */
            fechaVencimiento: string;
            /** @example 120 */
            cantidadDisponible: number;
            /**
             * @description Cero significa que vence HOY, y hoy todavia se puede entregar.
             * @example 34
             */
            diasParaVencer: number;
            /** @enum {string} */
            vencimiento: "VIGENTE" | "POR_VENCER" | "VENCIDO";
        };
        LoteVencidoDto: {
            /** Format: uuid */
            id: string;
            /** @example L-4471 */
            numeroLote: string;
            medicamento: components["schemas"]["MedicamentoDelLoteDto"];
            /** Format: date-time */
            fechaVencimiento: string;
            /** @example 45 */
            cantidadDisponible: number;
            /**
             * @description Dias transcurridos desde el vencimiento.
             * @example 12
             */
            diasVencido: number;
        };
        MedicamentoEntregadoDto: {
            /** @example AMOX500 */
            codigo: string;
            /** @example Amoxicilina */
            nombre: string;
            /** @enum {string} */
            unidad: "TABLETA" | "CAPSULA" | "JARABE_ML" | "AMPOLLA" | "FRASCO" | "SOBRE" | "UNIDAD" | "GRAMO";
            /**
             * @description Lote del que salio. Lo eligio el sistema por FEFO.
             * @example L-4471
             */
            numeroLote: string;
            /** Format: date-time */
            fechaVencimiento: string;
            /** @example 20 */
            cantidad: number;
        };
        EntregaDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            pacienteId: string;
            /**
             * Format: uuid
             * @description Copiada del paciente al momento de la entrega.
             */
            comunidadId: string;
            /** Format: date-time */
            fecha: string;
            /** Format: uuid */
            registradoPor: string;
            observaciones: string | null;
            medicamentos: components["schemas"]["MedicamentoEntregadoDto"][];
        };
        LineaEntregaDto: {
            medicamentoId: string;
            /** @example 20 */
            cantidad: number;
        };
        RegistrarEntregaDto: {
            pacienteId: string;
            /** @description Los medicamentos de la receta. El sistema elige los lotes por FEFO. */
            lineas: components["schemas"]["LineaEntregaDto"][];
            observaciones?: string;
        };
        MedicamentoDelMovimientoDto: {
            /** @example AMOX500 */
            codigo: string;
            nombreGenerico: string;
        };
        MovimientoInventarioDto: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            fecha: string;
            /** @enum {string} */
            tipo: "INGRESO" | "ENTREGA" | "AJUSTE" | "BAJA" | "DEVOLUCION";
            /**
             * @description NEGATIVA cuando la existencia baja (entrega, baja).
             * @example -20
             */
            cantidad: number;
            /**
             * @description Existencia del lote despues de aplicar este movimiento.
             * @example 300
             */
            cantidadResultante: number;
            motivo: string | null;
            /** Format: uuid */
            registradoPor: string;
            /**
             * Format: uuid
             * @description Presente solo en movimientos de ENTREGA.
             */
            entregaId: string | null;
            /** @example L-4471 */
            numeroLote: string;
            medicamento: components["schemas"]["MedicamentoDelMovimientoDto"];
        };
        RespuestaErrorDto: {
            /**
             * @description Codigo estable. El cliente decide que hacer segun este valor, no segun el mensaje.
             * @example VALIDACION
             * @enum {string}
             */
            codigo: "VALIDACION" | "NO_AUTENTICADO" | "SIN_PERMISO" | "NO_ENCONTRADO" | "CONFLICTO" | "DEMASIADAS_PETICIONES" | "ERROR_INTERNO";
            /**
             * @description Mensaje en espanol, apto para mostrarse tal cual al usuario.
             * @example La informacion enviada no es valida.
             */
            mensaje: string;
            /**
             * @description Detalle por campo. Presente sobre todo en errores de validacion.
             * @example [
             *       "dpi debe tener 13 digitos"
             *     ]
             */
            detalles?: string[];
            /**
             * @description Identificador de correlacion. Es lo que se busca en los logs para esta peticion.
             * @example 7f3a1c2e-9b4d-4e21-8a55-0c1d2e3f4a5b
             */
            trazaId: string;
            /** @example /v1/pacientes */
            ruta: string;
            /**
             * Format: date-time
             * @example 2026-08-26T15:04:05.000Z
             */
            fecha: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    SaludController_vivo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludVivoDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    SaludController_listo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludListoDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description La base de datos no responde. El gateway debe dejar de enviar trafico a esta instancia. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogoController_listar: {
        parameters: {
            query?: {
                /** @description Busca por inicio del nombre generico o del codigo. */
                buscar?: string;
                /** @description true para incluir los medicamentos desactivados. */
                incluirInactivos?: string;
                pagina?: number;
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["MedicamentoConExistenciaDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    CatalogoController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearMedicamentoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicamentoDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    CatalogoController_bajoMinimo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicamentoBajoMinimoDto"][];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    CatalogoController_obtener: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicamentoDetalleDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    CatalogoController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicamentoDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    LotesController_ingresar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                medicamentoId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngresarLoteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoteDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    LotesController_porVencer: {
        parameters: {
            query?: {
                /** @description Ventana de alerta. Por defecto DIAS_ALERTA_VENCIMIENTO; el tope es 365. */
                dias?: number;
                /** @description Empieza en 1. Por defecto 1. */
                pagina?: number;
                /** @description Por defecto 25. El servidor recorta cualquier valor mayor a 100. */
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordenados por vencimiento: primero el que vence antes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["LotePorVencerDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    LotesController_vencidos: {
        parameters: {
            query?: {
                /** @description Empieza en 1. Por defecto 1. */
                pagina?: number;
                /** @description Por defecto 25. El servidor recorta cualquier valor mayor a 100. */
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["LoteVencidoDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    LotesController_darDeBaja: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoteDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    EntregasController_listar: {
        parameters: {
            query?: {
                pacienteId?: string;
                comunidadId?: string;
                /** @description Empieza en 1. Por defecto 1. */
                pagina?: number;
                /** @description Por defecto 25. El servidor recorta cualquier valor mayor a 100. */
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["EntregaDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    EntregasController_registrar: {
        parameters: {
            query?: never;
            header: {
                authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarEntregaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntregaDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Otra persona de farmacia se adelanto con el mismo lote. Nada se descontó: reintente. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    EntregasController_obtener: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntregaDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    InventarioController_movimientos: {
        parameters: {
            query?: {
                loteId?: string;
                tipo?: "INGRESO" | "ENTREGA" | "AJUSTE" | "BAJA" | "DEVOLUCION";
                /** @description Empieza en 1. Por defecto 1. */
                pagina?: number;
                /** @description Por defecto 25. El servidor recorta cualquier valor mayor a 100. */
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Libro mayor. Es lo que se revisa cuando el conteo fisico no cuadra. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["MovimientoInventarioDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
}
