/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El proceso esta vivo */
        get: operations["SaludController_vivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/salud/listo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El servicio y sus dependencias responden */
        get: operations["SaludController_listo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/programas/hipertension": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inscripciones, con su ultimo control */
        get: operations["HipertensionController_listar"];
        put?: never;
        /** Inscribe a un paciente en el programa */
        post: operations["HipertensionController_inscribir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/programas/hipertension/atrasados": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pacientes que ya pasaron su fecha de proximo control */
        get: operations["HipertensionController_atrasados"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/programas/hipertension/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inscripcion por su identificador */
        get: operations["HipertensionController_obtener"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/programas/hipertension/{id}/controles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Controles del programa, lo mas reciente primero */
        get: operations["HipertensionController_listarControles"];
        put?: never;
        /**
         * Registra un control
         * @description La clasificacion y la fecha del proximo control las calcula el sistema; no se teclean.
         */
        post: operations["HipertensionController_registrarControl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/programas/hipertension/{id}/egreso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cierra la inscripcion en el programa */
        patch: operations["HipertensionController_egresar"];
        trace?: never;
    };
    "/v1/programas/embarazo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seguimientos, ordenados por fecha probable de parto */
        get: operations["EmbarazoController_listar"];
        put?: never;
        /**
         * Inscribe un embarazo
         * @description La FPP y la clasificacion de riesgo las calcula el sistema a partir de la FUM.
         */
        post: operations["EmbarazoController_inscribir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/programas/embarazo/alto-riesgo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Embarazos activos clasificados como de alto riesgo */
        get: operations["EmbarazoController_altoRiesgo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/programas/embarazo/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Seguimiento por su identificador */
        get: operations["EmbarazoController_obtener"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/programas/embarazo/{id}/controles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Controles prenatales, lo mas reciente primero */
        get: operations["EmbarazoController_listarControles"];
        put?: never;
        /**
         * Registra un control prenatal
         * @description Las semanas de gestacion, las senales de alarma y la fecha del proximo control las calcula el sistema.
         */
        post: operations["EmbarazoController_registrarControl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/programas/embarazo/{id}/cierre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cierra el seguimiento con su resultado */
        patch: operations["EmbarazoController_cerrar"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SaludVivoDto: {
            /**
             * @example vivo
             * @enum {string}
             */
            estado: "vivo";
            /** Format: date-time */
            fecha: string;
        };
        SaludListoDto: {
            /**
             * @example listo
             * @enum {string}
             */
            estado: "listo";
            /**
             * @description 'ok' cuando la base responde. Si no, el endpoint devuelve 503 en vez de este cuerpo.
             * @example ok
             */
            baseDatos: string;
        };
        PaginaDto: {
            /**
             * @description Pagina devuelta, empezando en 1.
             * @example 1
             */
            pagina: number;
            /**
             * @description Registros por pagina. El servidor recorta cualquier valor mayor al maximo.
             * @example 25
             */
            tamano: number;
            /**
             * @description Total de registros que cumplen el filtro.
             * @example 137
             */
            total: number;
            /**
             * @description Total de paginas. Nunca es menor que 1.
             * @example 6
             */
            totalPaginas: number;
        };
        UltimoControlHipertensionDto: {
            /** Format: date-time */
            fecha: string;
            /** @example 148 */
            sistolica: number;
            /** @example 94 */
            diastolica: number;
            /**
             * @description Calculada a partir de las cifras, nunca tecleada.
             * @enum {string}
             */
            clasificacion: "NORMAL" | "ELEVADA" | "ESTADIO_1" | "ESTADIO_2" | "CRISIS";
            /** @description true si la lectura alcanza la meta acordada. */
            enMeta: boolean;
            /** Format: date-time */
            proximoControl: string | null;
        };
        ProgramaHipertensionResumenDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            pacienteId: string;
            /** Format: uuid */
            comunidadId: string;
            /** Format: date-time */
            fechaIngreso: string;
            /** @enum {string} */
            estado: "ACTIVO" | "EGRESADO" | "ABANDONO" | "FALLECIDO" | "TRASLADADO";
            /** @example 140 */
            metaSistolica: number;
            /** @example 90 */
            metaDiastolica: number;
            ultimoControl: components["schemas"]["UltimoControlHipertensionDto"] | null;
        };
        HipertensoAtrasadoDto: {
            /** Format: uuid */
            programaId: string;
            /** Format: uuid */
            pacienteId: string;
            /** Format: uuid */
            comunidadId: string;
            /** Format: date-time */
            proximoControl: string;
            /**
             * @description Dias transcurridos desde la fecha en que debio venir.
             * @example 23
             */
            diasDeAtraso: number;
        };
        ProgramaHipertensionDto: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description Paciente del servicio usuarios. No es llave foranea.
             */
            pacienteId: string;
            /** Format: uuid */
            comunidadId: string;
            /** Format: date-time */
            fechaIngreso: string;
            /** @enum {string} */
            estado: "ACTIVO" | "EGRESADO" | "ABANDONO" | "FALLECIDO" | "TRASLADADO";
            /** Format: date-time */
            fechaEgreso: string | null;
            motivoEgreso: string | null;
            /**
             * @description Meta acordada con el paciente, no un valor fijo del sistema.
             * @example 140
             */
            metaSistolica: number;
            /** @example 90 */
            metaDiastolica: number;
            /** Format: uuid */
            inscritoPor: string;
            /** Format: date-time */
            creadoEn: string;
        };
        InscribirHipertensionDto: {
            /** @description Identificador del paciente en el servicio de usuarios */
            pacienteId: string;
            /**
             * @description Meta de presion sistolica acordada
             * @default 140
             */
            metaSistolica: number;
            /** @default 90 */
            metaDiastolica: number;
        };
        ControlHipertensionDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programaId: string;
            /** Format: date-time */
            fecha: string;
            /** @example 148 */
            sistolica: number;
            /** @example 94 */
            diastolica: number;
            /** @enum {string} */
            clasificacion: "NORMAL" | "ELEVADA" | "ESTADIO_1" | "ESTADIO_2" | "CRISIS";
            enMeta: boolean;
            /**
             * Format: decimal
             * @example 72.50
             */
            pesoKg: string | null;
            /** @description Si el paciente refiere tomar el tratamiento. */
            adherencia: boolean | null;
            /**
             * Format: date-time
             * @description Calculado segun la clasificacion.
             */
            proximoControl: string | null;
            /** Format: uuid */
            registradoPor: string;
            /** @description Descifradas. En la base son ilegibles. */
            observaciones: string | null;
        };
        RegistrarControlHipertensionDto: {
            /** @example 148 */
            sistolica: number;
            /** @example 94 */
            diastolica: number;
            pesoKg?: number;
            /** @description Si el paciente refiere estar tomando el tratamiento */
            adherencia?: boolean;
            observaciones?: string;
            /**
             * Format: date-time
             * @description Fecha real del control. Se usa al digitalizar papel.
             */
            fecha?: string;
        };
        UltimoControlPrenatalDto: {
            /** Format: date-time */
            fecha: string;
            /** @example 24 */
            semanasGestacion: number;
            /** Format: date-time */
            proximoControl: string | null;
            /** @description Senales de alarma detectadas por el sistema. */
            alertas: string[];
        };
        ProgramaEmbarazoResumenDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            pacienteId: string;
            /** Format: uuid */
            comunidadId: string;
            /** Format: date-time */
            fum: string;
            /** Format: date-time */
            fpp: string;
            /** @enum {string} */
            riesgo: "BAJO" | "ALTO";
            motivoRiesgo: string | null;
            /** @enum {string} */
            estado: "ACTIVO" | "EGRESADO" | "ABANDONO" | "FALLECIDO" | "TRASLADADO";
            /** @example 3 */
            numeroGestacion: number;
            /** @example 24 */
            semanasGestacion: number;
            ultimoControl: components["schemas"]["UltimoControlPrenatalDto"] | null;
        };
        ProgramaEmbarazoDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            pacienteId: string;
            /** Format: uuid */
            comunidadId: string;
            /**
             * Format: date-time
             * @description Fecha de ultima menstruacion.
             */
            fum: string;
            /**
             * Format: date-time
             * @description Fecha probable de parto: FUM + 280 dias (regla de Naegele).
             */
            fpp: string;
            /** @example 3 */
            numeroGestacion: number;
            /** @example 2 */
            partosPrevios: number;
            /** @enum {string} */
            riesgo: "BAJO" | "ALTO";
            /** @description Por que se clasifico como alto riesgo, para que el siguiente turno sepa a que atenerse. */
            motivoRiesgo: string | null;
            /** @enum {string} */
            estado: "ACTIVO" | "EGRESADO" | "ABANDONO" | "FALLECIDO" | "TRASLADADO";
            /** @enum {string|null} */
            resultado: "PARTO_NORMAL" | "CESAREA" | "ABORTO" | "OBITO" | "TRASLADO" | "OTRO" | null;
            /** Format: date-time */
            fechaCierre: string | null;
            /** Format: uuid */
            inscritoPor: string;
            /** Format: date-time */
            creadoEn: string;
            /**
             * @description Calculada al responder sobre el dia local, no almacenada.
             * @example 24
             */
            semanasGestacion: number;
        };
        InscribirEmbarazoDto: {
            pacienteId: string;
            /**
             * Format: date-time
             * @description Fecha de ultima menstruacion. De aqui salen la FPP y las semanas de gestacion.
             * @example 2026-01-15
             */
            fum: string;
            /** @default 1 */
            numeroGestacion: number;
            /** @default 0 */
            partosPrevios: number;
        };
        EmbarazoInscritoDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            pacienteId: string;
            /** Format: uuid */
            comunidadId: string;
            /**
             * Format: date-time
             * @description Fecha de ultima menstruacion.
             */
            fum: string;
            /**
             * Format: date-time
             * @description Fecha probable de parto: FUM + 280 dias (regla de Naegele).
             */
            fpp: string;
            /** @example 3 */
            numeroGestacion: number;
            /** @example 2 */
            partosPrevios: number;
            /** @enum {string} */
            riesgo: "BAJO" | "ALTO";
            /** @description Por que se clasifico como alto riesgo, para que el siguiente turno sepa a que atenerse. */
            motivoRiesgo: string | null;
            /** @enum {string} */
            estado: "ACTIVO" | "EGRESADO" | "ABANDONO" | "FALLECIDO" | "TRASLADADO";
            /** @enum {string|null} */
            resultado: "PARTO_NORMAL" | "CESAREA" | "ABORTO" | "OBITO" | "TRASLADO" | "OTRO" | null;
            /** Format: date-time */
            fechaCierre: string | null;
            /** Format: uuid */
            inscritoPor: string;
            /** Format: date-time */
            creadoEn: string;
            /**
             * @description Calculada al responder sobre el dia local, no almacenada.
             * @example 24
             */
            semanasGestacion: number;
            /**
             * @description Vacio cuando el riesgo es bajo.
             * @example [
             *       "Edad menor de 18 anios"
             *     ]
             */
            motivosRiesgo: string[];
        };
        ControlPrenatalDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            programaId: string;
            /** Format: date-time */
            fecha: string;
            /**
             * @description Calculadas a partir de la FUM y la fecha del control.
             * @example 24
             */
            semanasGestacion: number;
            /**
             * Format: decimal
             * @example 58.30
             */
            pesoKg: string | null;
            sistolica: number | null;
            diastolica: number | null;
            /**
             * Format: decimal
             * @description Altura uterina en centimetros.
             * @example 24.0
             */
            alturaUterinaCm: string | null;
            /**
             * @description Frecuencia cardiaca fetal, latidos por minuto.
             * @example 140
             */
            fcf: number | null;
            edema: boolean | null;
            /** @description Senales de alarma detectadas por el sistema en este control. */
            alertas: string[];
            /** Format: date-time */
            proximoControl: string | null;
            /** Format: uuid */
            registradoPor: string;
            /** @description Descifradas. */
            observaciones: string | null;
        };
        RegistrarControlPrenatalDto: {
            pesoKg?: number;
            sistolica?: number;
            diastolica?: number;
            /** @description Altura uterina en centimetros */
            alturaUterinaCm?: number;
            /** @description Frecuencia cardiaca fetal */
            fcf?: number;
            edema?: boolean;
            observaciones?: string;
            /** Format: date-time */
            fecha?: string;
        };
        ProgramaEmbarazoBaseDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            pacienteId: string;
            /** Format: uuid */
            comunidadId: string;
            /**
             * Format: date-time
             * @description Fecha de ultima menstruacion.
             */
            fum: string;
            /**
             * Format: date-time
             * @description Fecha probable de parto: FUM + 280 dias (regla de Naegele).
             */
            fpp: string;
            /** @example 3 */
            numeroGestacion: number;
            /** @example 2 */
            partosPrevios: number;
            /** @enum {string} */
            riesgo: "BAJO" | "ALTO";
            /** @description Por que se clasifico como alto riesgo, para que el siguiente turno sepa a que atenerse. */
            motivoRiesgo: string | null;
            /** @enum {string} */
            estado: "ACTIVO" | "EGRESADO" | "ABANDONO" | "FALLECIDO" | "TRASLADADO";
            /** @enum {string|null} */
            resultado: "PARTO_NORMAL" | "CESAREA" | "ABORTO" | "OBITO" | "TRASLADO" | "OTRO" | null;
            /** Format: date-time */
            fechaCierre: string | null;
            /** Format: uuid */
            inscritoPor: string;
            /** Format: date-time */
            creadoEn: string;
        };
        RespuestaErrorDto: {
            /**
             * @description Codigo estable. El cliente decide que hacer segun este valor, no segun el mensaje.
             * @example VALIDACION
             * @enum {string}
             */
            codigo: "VALIDACION" | "NO_AUTENTICADO" | "SIN_PERMISO" | "NO_ENCONTRADO" | "CONFLICTO" | "DEMASIADAS_PETICIONES" | "ERROR_INTERNO";
            /**
             * @description Mensaje en espanol, apto para mostrarse tal cual al usuario.
             * @example La informacion enviada no es valida.
             */
            mensaje: string;
            /**
             * @description Detalle por campo. Presente sobre todo en errores de validacion.
             * @example [
             *       "dpi debe tener 13 digitos"
             *     ]
             */
            detalles?: string[];
            /**
             * @description Identificador de correlacion. Es lo que se busca en los logs para esta peticion.
             * @example 7f3a1c2e-9b4d-4e21-8a55-0c1d2e3f4a5b
             */
            trazaId: string;
            /** @example /v1/pacientes */
            ruta: string;
            /**
             * Format: date-time
             * @example 2026-08-26T15:04:05.000Z
             */
            fecha: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    SaludController_vivo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludVivoDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    SaludController_listo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludListoDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description La base de datos no responde. El gateway debe dejar de enviar trafico a esta instancia. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HipertensionController_listar: {
        parameters: {
            query?: {
                estado?: "ACTIVO" | "EGRESADO" | "ABANDONO" | "FALLECIDO" | "TRASLADADO";
                comunidadId?: string;
                /** @description Empieza en 1. Por defecto 1. */
                pagina?: number;
                /** @description Por defecto 25. El servidor recorta cualquier valor mayor a 100. */
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El ultimo control viene incrustado: evita el N+1 de esta pantalla. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["ProgramaHipertensionResumenDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    HipertensionController_inscribir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InscribirHipertensionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramaHipertensionDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    HipertensionController_atrasados: {
        parameters: {
            query?: {
                /** @description Empieza en 1. Por defecto 1. */
                pagina?: number;
                /** @description Por defecto 25. El servidor recorta cualquier valor mayor a 100. */
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordenados del mas atrasado al menos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["HipertensoAtrasadoDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    HipertensionController_obtener: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramaHipertensionDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    HipertensionController_listarControles: {
        parameters: {
            query?: {
                /** @description Empieza en 1. Por defecto 1. */
                pagina?: number;
                /** @description Por defecto 25. El servidor recorta cualquier valor mayor a 100. */
                tamano?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["ControlHipertensionDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    HipertensionController_registrarControl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarControlHipertensionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlHipertensionDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    HipertensionController_egresar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramaHipertensionDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    EmbarazoController_listar: {
        parameters: {
            query?: {
                estado?: "ACTIVO" | "EGRESADO" | "ABANDONO" | "FALLECIDO" | "TRASLADADO";
                riesgo?: "BAJO" | "ALTO";
                comunidadId?: string;
                /** @description Empieza en 1. Por defecto 1. */
                pagina?: number;
                /** @description Por defecto 25. El servidor recorta cualquier valor mayor a 100. */
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["ProgramaEmbarazoResumenDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    EmbarazoController_inscribir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InscribirEmbarazoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmbarazoInscritoDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    EmbarazoController_altoRiesgo: {
        parameters: {
            query?: {
                /** @description Empieza en 1. Por defecto 1. */
                pagina?: number;
                /** @description Por defecto 25. El servidor recorta cualquier valor mayor a 100. */
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["ProgramaEmbarazoResumenDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    EmbarazoController_obtener: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramaEmbarazoDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    EmbarazoController_listarControles: {
        parameters: {
            query?: {
                /** @description Empieza en 1. Por defecto 1. */
                pagina?: number;
                /** @description Por defecto 25. El servidor recorta cualquier valor mayor a 100. */
                tamano?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["ControlPrenatalDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    EmbarazoController_registrarControl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarControlPrenatalDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlPrenatalDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    EmbarazoController_cerrar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sin semanasGestacion: el seguimiento ya cerro, la cuenta dejo de correr. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramaEmbarazoBaseDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
}
