/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El proceso esta vivo */
        get: operations["SaludController_vivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/salud/listo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El servicio y sus dependencias responden */
        get: operations["SaludController_listo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consulta la bitacora, paginada
         * @description Orden descendente: lo mas reciente primero, que es como se audita.
         */
        get: operations["RegistrosController_consultar"];
        put?: never;
        /**
         * Agrega una entrada a la bitacora
         * @description Encadena la entrada al ultimo registro existente. El usuario y el rol se toman del token, no del cuerpo. Los valores anterior y nuevo se cifran antes de guardarse.
         */
        post: operations["RegistrosController_registrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registros/verificacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recorre la cadena y reporta si esta intacta
         * @description Devuelve el numero del primer registro que no cuadra, si lo hay. No necesita las llaves de descifrado: el hash cubre el texto cifrado.
         */
        get: operations["RegistrosController_verificar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/raices/cierre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cierra un dia y firma su hash raiz
         * @description Sin `dia`, cierra el de ayer. No cierra el dia en curso: todavia puede recibir registros, y la firma quedaria invalidada por el siguiente que entrara.
         */
        post: operations["RaicesController_cerrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/raices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Raices diarias firmadas
         * @description Cada una trae `firmaValida`, resultado de recomprobarla con LLAVE_RAIZ_TRAZA. Una raiz con la firma rota significa que alguien reescribio ese dia.
         */
        get: operations["RaicesController_listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegistrarRegistroDto: {
            /**
             * @description Servicio que origino la accion.
             * @enum {string}
             */
            servicio: "auth" | "usuarios" | "programas" | "medicamentos" | "reportes" | "cms";
            /** @enum {string} */
            accion: "CONSULTA" | "CREACION" | "MODIFICACION" | "ELIMINACION" | "IMPRESION" | "EXPORTACION";
            /**
             * @description Tipo de dato tocado.
             * @example expediente
             */
            entidad: string;
            /**
             * @description Id del dato en el servicio de origen.
             * @example exp-000123
             */
            entidadId: string;
            /**
             * @description Por que se hizo. §10.4 lo exige junto con usuario, fecha y accion. Obligatorio para consultas de expediente e impresiones.
             * @example Correccion tras revision medica
             */
            motivo?: string;
            /**
             * @description Valor antes del cambio, EN CLARO. El servicio lo cifra antes de guardarlo; nunca queda legible en la base.
             * @example Hipertension arterial leve
             */
            valorAnterior?: string;
            /**
             * @description Valor despues del cambio, en claro.
             * @example Hipertension arterial moderada
             */
            valorNuevo?: string;
            /**
             * @description Cuando ocurrio en el servicio de origen. Si no se envia, se toma el momento de la recepcion.
             * @example 2026-08-26T18:23:27.531Z
             */
            ocurridoEn?: string;
            /**
             * @description IP del cliente que origino la accion.
             * @example 10.0.0.5
             */
            ip?: string;
        };
        RegistroDto: {
            /** @example 1042 */
            numero: string;
            /**
             * @description El hash de la entrada anterior. Es lo que encadena la bitacora.
             * @example a3f1...
             */
            hashPrevio: string;
            /** @example 9b7c... */
            hash: string;
            /**
             * @description Que servicio origino la accion.
             * @example usuarios
             */
            servicio: string;
            /** @enum {string} */
            accion: "CONSULTA" | "CREACION" | "MODIFICACION" | "ELIMINACION" | "IMPRESION" | "EXPORTACION";
            /** @example expediente */
            entidad: string;
            /** @example exp-000123 */
            entidadId: string;
            /** @description Quien la ejecuto, del token; nunca del cuerpo de la peticion. */
            usuarioId: string;
            /** @example MEDICO */
            usuarioRol: string;
            motivo: string | null;
            valorAnterior: string | null;
            valorNuevo: string | null;
            /** @description Une en un mismo hilo todo lo que provoco una sola peticion. */
            trazaId: string;
            ip: string | null;
            /** Format: date-time */
            registradoEn: string;
        };
        PaginaDto: {
            /**
             * @description Pagina devuelta, empezando en 1.
             * @example 1
             */
            pagina: number;
            /**
             * @description Registros por pagina. El servidor recorta cualquier valor mayor al maximo.
             * @example 25
             */
            tamano: number;
            /**
             * @description Total de registros que cumplen el filtro.
             * @example 137
             */
            total: number;
            /**
             * @description Total de paginas. Nunca es menor que 1.
             * @example 6
             */
            totalPaginas: number;
        };
        VerificacionDto: {
            /** @description Falso en cuanto una entrada no cuadra con la anterior. */
            intacta: boolean;
            /**
             * @description Cuantas entradas se recorrieron.
             * @example 1042
             */
            revisados: number;
            /**
             * @description El numero de la primera entrada que no cuadra, si la hay.
             * @example 318
             */
            rotoEn: string | null;
        };
        CerrarDiaDto: {
            /**
             * @description Dia a cerrar, AAAA-MM-DD. Si se omite, se cierra el de ayer.
             * @example 2026-08-25
             */
            dia?: string;
        };
        RaizDiariaDto: {
            /**
             * Format: date
             * @example 2026-09-17
             */
            dia: string;
            /** @example 901 */
            numeroDesde: string;
            /** @example 1042 */
            numeroHasta: string;
            /**
             * @description Cuantas entradas entraron ese dia.
             * @example 142
             */
            cantidad: number;
            /**
             * @description El hash de la ultima entrada del dia: el sello de la jornada.
             * @example 9b7c...
             */
            hashFinal: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    SaludController_vivo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SaludController_listo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RegistrosController_consultar: {
        parameters: {
            query?: {
                servicio?: string;
                accion?: "CONSULTA" | "CREACION" | "MODIFICACION" | "ELIMINACION" | "IMPRESION" | "EXPORTACION";
                entidad?: string;
                entidadId?: string;
                /** @description Quien ejecuto la accion. */
                usuarioId?: string;
                /** @description Desde (inclusive), ISO-8601. */
                desde?: string;
                /** @description Hasta (inclusive), ISO-8601. */
                hasta?: string;
                pagina?: number;
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["RegistroDto"][];
                    };
                };
            };
        };
    };
    RegistrosController_registrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarRegistroDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroDto"];
                };
            };
        };
    };
    RegistrosController_verificar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerificacionDto"];
                };
            };
        };
    };
    RaicesController_cerrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CerrarDiaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaizDiariaDto"];
                };
            };
        };
    };
    RaicesController_listar: {
        parameters: {
            query?: {
                pagina?: number;
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["RaizDiariaDto"][];
                    };
                };
            };
        };
    };
}
