/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El proceso esta vivo */
        get: operations["SaludController_vivo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/salud/listo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** El servicio y sus dependencias responden */
        get: operations["SaludController_listo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/comunidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Comunidades que atiende el CAP
         * @description Por defecto solo las activas. Con ?todas=true incluye las dadas de baja.
         */
        get: operations["ComunidadesController_listar"];
        put?: never;
        /** Registra una comunidad */
        post: operations["ComunidadesController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pacientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca pacientes por DPI, inicio de nombre o comunidad
         * @description La busqueda por DPI se resuelve con el indice ciego sobre el campo cifrado.
         */
        get: operations["PacientesController_buscar"];
        put?: never;
        /** Registra un paciente y abre su expediente */
        post: operations["PacientesController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pacientes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ficha completa del paciente */
        get: operations["PacientesController_obtener"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Corrige datos del paciente */
        patch: operations["PacientesController_actualizar"];
        trace?: never;
    };
    "/v1/grupos-familiares": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista paginada de grupos familiares */
        get: operations["GruposController_listar"];
        put?: never;
        /** Crea un grupo familiar */
        post: operations["GruposController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/grupos-familiares/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Grupo familiar con sus integrantes */
        get: operations["GruposController_obtener"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/expedientes/buscar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Busca un expediente por su numero
         * @description El numero esta cifrado en la base; se resuelve por su indice ciego.
         */
        get: operations["ExpedientesController_porNumero"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/expedientes/{expedienteId}/atenciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historial del expediente, lo mas reciente primero */
        get: operations["AtencionesController_listar"];
        put?: never;
        /** Registra una atencion en el expediente */
        post: operations["AtencionesController_registrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/digitalizacion/resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Avance de la digitalizacion de expedientes */
        get: operations["DigitalizacionController_resumen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/digitalizacion/{expedienteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cambia el estado de digitalizacion de un expediente */
        patch: operations["DigitalizacionController_actualizar"];
        trace?: never;
    };
    "/v1/fichas/catalogo/{tipo}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estructura de una ficha: signos de peligro, antecedentes y problemas
         * @description Todo lo que la pantalla necesita para dibujarse, en una sola respuesta. Los textos vienen tal cual estan impresos en el formulario oficial.
         */
        get: operations["FichasController_catalogo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/expedientes/{expedienteId}/fichas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registra una ficha clinica completa
         * @description La ficha entera se guarda en una sola transaccion. Los identificadores de signos, problemas y diagnosticos se validan contra el catalogo de ESA ficha: no se puede guardar un problema de la ficha de neonatos dentro de una de adultos.
         */
        post: operations["FichasController_registrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fichas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Una ficha registrada, con el texto descifrado y el catalogo resuelto
         * @description El IMC viene calculado de peso y talla; no se guarda en la base.
         */
        get: operations["FichasController_obtener"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SaludVivoDto: {
            /**
             * @example vivo
             * @enum {string}
             */
            estado: "vivo";
            /** Format: date-time */
            fecha: string;
        };
        SaludListoDto: {
            /**
             * @example listo
             * @enum {string}
             */
            estado: "listo";
            /**
             * @description 'ok' cuando la base responde. Si no, el endpoint devuelve 503 en vez de este cuerpo.
             * @example ok
             */
            baseDatos: string;
        };
        ComunidadDto: {
            /** Format: uuid */
            id: string;
            /** @example Purulha Centro */
            nombre: string;
            /** @description Codigo interno del CAP, si lo tiene. */
            codigo?: string | null;
            /** @description Comunidad lejana al CAP. Cambia la prioridad de seguimiento: a quien vive lejos no se le cita por gusto. */
            distante: boolean;
            /** @description Una comunidad inactiva ya no aparece al registrar pacientes. */
            activa: boolean;
        };
        CrearComunidadDto: {
            /** @example Chilasco */
            nombre: string;
            /** @example CHI-01 */
            codigo?: string;
            /** @description Comunidad de dificil acceso. Se usa para priorizar visitas y seguimiento. */
            distante?: boolean;
        };
        PaginaDto: {
            /**
             * @description Pagina devuelta, empezando en 1.
             * @example 1
             */
            pagina: number;
            /**
             * @description Registros por pagina. El servidor recorta cualquier valor mayor al maximo.
             * @example 25
             */
            tamano: number;
            /**
             * @description Total de registros que cumplen el filtro.
             * @example 137
             */
            total: number;
            /**
             * @description Total de paginas. Nunca es menor que 1.
             * @example 6
             */
            totalPaginas: number;
        };
        ComunidadResumenDto: {
            /** Format: uuid */
            id: string;
            /** @example Purulha Centro */
            nombre: string;
        };
        ExpedienteResumenDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Descifrado al vuelo. En la base vive cifrado.
             * @example EXP-2026-000123
             */
            numero: string;
        };
        PacienteResumenDto: {
            /** Format: uuid */
            id: string;
            nombres: string;
            apellidos: string;
            /** Format: date-time */
            fechaNacimiento: string;
            /**
             * @description Calculada al momento de responder.
             * @example 34
             */
            edad: number;
            /** @example F */
            sexo: string;
            /**
             * @description Idioma de atencion. En Purulha buena parte del padron habla q eqchi.
             * @example ES
             */
            idioma: string;
            fallecido: boolean;
            comunidad: components["schemas"]["ComunidadResumenDto"];
            expediente: components["schemas"]["ExpedienteResumenDto"] | null;
        };
        GrupoResumenDto: {
            /** Format: uuid */
            id: string;
            /** @example GF-2026-000045 */
            codigo: string;
        };
        ExpedienteDePacienteDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Descifrado al vuelo. En la base vive cifrado.
             * @example EXP-2026-000123
             */
            numero: string;
            /**
             * Format: date-time
             * @description Apertura del expediente EN PAPEL, que puede ser muy anterior a la digitalizacion. null cuando no se conoce: los expedientes viejos no siempre la traen.
             */
            aperturaEn: string | null;
        };
        PacienteDto: {
            /** Format: uuid */
            id: string;
            /** @description null cuando el paciente no tiene DPI registrado. */
            dpi: string | null;
            nombres: string;
            apellidos: string;
            /** Format: date-time */
            fechaNacimiento: string;
            /** @example 34 */
            edad: number;
            /** @example F */
            sexo: string;
            /** @example ES */
            idioma: string;
            telefono: string | null;
            fallecido: boolean;
            comunidad: components["schemas"]["ComunidadResumenDto"];
            grupoFamiliar: components["schemas"]["GrupoResumenDto"] | null;
            expediente: components["schemas"]["ExpedienteDePacienteDto"] | null;
        };
        CrearPacienteDto: {
            /**
             * @description DPI de 13 digitos. OPCIONAL: los ninos y parte de la poblacion rural no lo tienen.
             * @example 1234567890101
             */
            dpi?: string;
            /** @example Juana Isabel */
            nombres: string;
            /** @example Perez Caal */
            apellidos: string;
            /**
             * Format: date-time
             * @example 1985-04-12
             */
            fechaNacimiento: string;
            /** @enum {string} */
            sexo: "M" | "F";
            /**
             * @default ESPANOL
             * @enum {string}
             */
            idioma: "ESPANOL" | "POQOMCHI" | "QEQCHI" | "OTRO";
            /** @description Identificador de la comunidad */
            comunidadId: string;
            grupoFamiliarId?: string;
            telefono?: string;
            /** @description Numero del expediente de papel. Se usa al digitalizar; si se omite, el sistema genera uno. */
            numeroExpediente?: string;
            /** @description Marca el expediente como proveniente de papel (RF-08). */
            digitalizado?: boolean;
        };
        PacienteCreadoDto: {
            /** Format: uuid */
            id: string;
            /** @example EXP-2026-000123 */
            numeroExpediente: string;
            /** Format: uuid */
            expedienteId: string;
        };
        ActualizarPacienteDto: {
            nombres?: string;
            apellidos?: string;
            /** @enum {string} */
            idioma?: "ESPANOL" | "POQOMCHI" | "QEQCHI" | "OTRO";
            comunidadId?: string;
            grupoFamiliarId?: string;
            telefono?: string;
            fallecido?: boolean;
        };
        GrupoFamiliarResumenDto: {
            /** Format: uuid */
            id: string;
            /** @example GF-2026-000045 */
            codigo: string;
            direccion: string | null;
            telefono: string | null;
            comunidad: components["schemas"]["ComunidadResumenDto"];
            /**
             * @description Contado en la base de datos, no trayendo a los integrantes: evita el N+1 de esta pantalla.
             * @example 5
             */
            integrantes: number;
        };
        IntegranteDto: {
            /** Format: uuid */
            id: string;
            nombres: string;
            apellidos: string;
            /** Format: date-time */
            fechaNacimiento: string;
            /** @example M */
            sexo: string;
            fallecido: boolean;
            /** @example 12 */
            edad: number;
        };
        GrupoFamiliarDto: {
            /** Format: uuid */
            id: string;
            /** @example GF-2026-000045 */
            codigo: string;
            direccion: string | null;
            telefono: string | null;
            comunidad: components["schemas"]["ComunidadResumenDto"];
            /** @description Ordenados del mayor al menor. */
            integrantes: components["schemas"]["IntegranteDto"][];
        };
        CrearGrupoDto: {
            /** @description Codigo del grupo familiar segun el registro del CAP. Si se omite, el sistema genera uno. */
            codigo?: string;
            comunidadId: string;
            /** @example Caserio El Rejon, casa 14 */
            direccion?: string;
            telefono?: string;
        };
        GrupoFamiliarCreadoDto: {
            /** Format: uuid */
            id: string;
            /** @example GF-2026-000045 */
            codigo: string;
            direccion: string | null;
            telefono: string | null;
            /** Format: uuid */
            comunidadId: string;
        };
        PacienteDelExpedienteDto: {
            /** Format: uuid */
            id: string;
            nombres: string;
            apellidos: string;
            /** Format: date-time */
            fechaNacimiento: string;
            /** @example F */
            sexo: string;
            comunidad: components["schemas"]["ComunidadResumenDto"];
        };
        DigitalizacionDelExpedienteDto: {
            /** @enum {string} */
            estado: "PENDIENTE" | "EN_PROCESO" | "COMPLETO" | "NO_LOCALIZADO";
            digitalizadoPor: string | null;
            /** Format: date-time */
            iniciadoEn: string | null;
            /** Format: date-time */
            completadoEn: string | null;
            /** @description Cuantas atenciones del papel se transcribieron. */
            atencionesTranscritas: number;
            observaciones: string | null;
        };
        ExpedienteEncontradoDto: {
            /** Format: uuid */
            id: string;
            /** @example EXP-2026-000123 */
            numero: string;
            /**
             * Format: date-time
             * @description Apertura del expediente en papel. null cuando no se conoce.
             */
            aperturaEn: string | null;
            paciente: components["schemas"]["PacienteDelExpedienteDto"];
            digitalizacion: components["schemas"]["DigitalizacionDelExpedienteDto"] | null;
        };
        AtencionDto: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            fecha: string;
            /**
             * Format: uuid
             * @description Usuario del sistema que la registro.
             */
            registradaPor: string;
            /** @description true si proviene de transcribir una atencion en papel. */
            digitalizada: boolean;
            /** @description Descifrado. En la base es ilegible. */
            motivo: string | null;
            diagnostico: string | null;
            tratamiento: string | null;
            notas: string | null;
            /**
             * Format: decimal
             * @example 72.5
             */
            pesoKg: string | null;
            /**
             * Format: decimal
             * @example 158.0
             */
            tallaCm: string | null;
            /** @example 148 */
            presionSistolica: number | null;
            /** @example 94 */
            presionDiastolica: number | null;
            /**
             * Format: decimal
             * @example 37.2
             */
            temperaturaC: string | null;
        };
        RegistrarAtencionDto: {
            /** @example Control de presion arterial */
            motivo: string;
            diagnostico?: string;
            tratamiento?: string;
            notas?: string;
            pesoKg?: number;
            tallaCm?: number;
            presionSistolica?: number;
            presionDiastolica?: number;
            temperaturaC?: number;
            /**
             * Format: date-time
             * @description Fecha real de la atencion. Se usa al digitalizar papel: la consulta ocurrio hace anos.
             */
            fecha?: string;
            /** @description Marca la atencion como transcrita desde papel. */
            digitalizada?: boolean;
        };
        ConteoPorEstadoDto: {
            /** @example 1240 */
            PENDIENTE: number;
            /** @example 85 */
            EN_PROCESO: number;
            /** @example 613 */
            COMPLETO: number;
            /**
             * @description Expedientes que el personal no encontro en el archivo fisico.
             * @example 12
             */
            NO_LOCALIZADO: number;
        };
        ResumenDigitalizacionDto: {
            /** @example 1950 */
            total: number;
            porEstado: components["schemas"]["ConteoPorEstadoDto"];
            /**
             * @description Con un decimal. 0 cuando todavia no hay expedientes.
             * @example 31.4
             */
            porcentajeCompleto: number;
        };
        ActualizarDigitalizacionDto: {
            /** @enum {string} */
            estado: "PENDIENTE" | "EN_PROCESO" | "COMPLETO" | "NO_LOCALIZADO";
            observaciones?: string;
        };
        RegistroDigitalizacionDto: {
            /** Format: uuid */
            expedienteId: string;
            /** @enum {string} */
            estado: "PENDIENTE" | "EN_PROCESO" | "COMPLETO" | "NO_LOCALIZADO";
            digitalizadoPor: string | null;
            /** Format: date-time */
            iniciadoEn: string | null;
            /** Format: date-time */
            completadoEn: string | null;
            /** @example 7 */
            atencionesTranscritas: number;
            observaciones: string | null;
        };
        SignoPeligroCatalogoDto: {
            /** Format: uuid */
            id: string;
            /** @description Orden en que aparece en el formulario impreso. */
            orden: number;
            /** @description Texto tal cual esta impreso en el papel. */
            texto: string;
            /** @description true en "Otros (describir)". */
            pideTexto: boolean;
        };
        AntecedenteCatalogoDto: {
            /** Format: uuid */
            id: string;
            /**
             * @description Identificador estable, citable desde los reportes.
             * @example MED_DIABETES
             */
            codigo: string;
            /** @enum {string} */
            grupo: "MEDICO" | "FAMILIAR" | "HABITO";
            orden: number;
            /** @example Hipertensión arterial */
            texto: string;
            /** @description Pide escribir "cual". */
            pideDetalle: boolean;
            /** @description Pide la fecha de la ultima vez. */
            pideFecha: boolean;
            /** @description Pide una cantidad: dosis, cigarrillos al dia. */
            pideNumero: boolean;
            /** @description El papel ofrece "No aplica" ademas de SI y NO. */
            permiteNoAplica: boolean;
        };
        OpcionCatalogoDto: {
            /** Format: uuid */
            id: string;
            /** @description Orden en que aparece en el formulario impreso. */
            orden: number;
            /** @description Texto tal cual esta impreso en el papel. */
            texto: string;
        };
        DiagnosticoCatalogoDto: {
            /** Format: uuid */
            id: string;
            /** @description Orden en que aparece en el formulario impreso. */
            orden: number;
            /** @description Texto tal cual esta impreso en el papel. */
            texto: string;
            /** @description true en las opciones "Otro: ____", que piden escribir cual. */
            pideTexto: boolean;
        };
        ProblemaCatalogoDto: {
            /** Format: uuid */
            id: string;
            orden: number;
            /** @example Tos o dificultad para respirar */
            nombre: string;
            /** @description Lo que en el papel se subraya en EVALUAR. */
            signos: components["schemas"]["OpcionCatalogoDto"][];
            /** @description Lo que se subraya en CLASIFICAR. */
            diagnosticos: components["schemas"]["DiagnosticoCatalogoDto"][];
        };
        CatalogoFichaDto: {
            /** @enum {string} */
            tipoFicha: "ADULTO" | "NEONATO" | "NINEZ" | "PRENATAL";
            signosPeligro: components["schemas"]["SignoPeligroCatalogoDto"][];
            antecedentes: components["schemas"]["AntecedenteCatalogoDto"][];
            problemas: components["schemas"]["ProblemaCatalogoDto"][];
        };
        SignoPeligroEvaluadoDto: {
            /** Format: uuid */
            signoId: string;
            presente: boolean;
            /** @description Solo en el signo "Otros (describir)". */
            detalle?: string;
        };
        ProblemaEvaluadoDto: {
            /** Format: uuid */
            problemaId: string;
            /** @description La casilla SI/NO de la primera columna. */
            presente: boolean;
            signoIds?: string[];
            diagnosticoIds?: string[];
            /** @description El texto de las opciones "Otro: ____". */
            otroDiagnostico?: string;
            /** @description Conducta indicada para este problema. */
            conducta?: string;
        };
        MedicamentoIndicadoDto: {
            /** @example Amoxicilina 500 mg */
            nombre: string;
            /** @example 1 tableta cada 8 horas */
            dosis?: string;
            /** @example 7 */
            dias?: number;
        };
        CrearFichaDto: {
            /** @enum {string} */
            tipoFicha: "ADULTO" | "NEONATO" | "NINEZ" | "PRENATAL";
            /**
             * Format: date-time
             * @description Por defecto, ahora. Se indica al digitalizar papel.
             */
            fecha?: string;
            /** @description true si proviene de transcribir un expediente de papel. */
            digitalizada?: boolean;
            /** @description Seccion V. Motivo de la consulta. */
            motivo: string;
            /** @description Seccion VI. Historia de la enfermedad actual. */
            historiaEnfermedad?: string;
            /** @description Seccion IV. Solo si el paciente fue referido. */
            manejoEstabilizacion?: string;
            signosPeligro?: components["schemas"]["SignoPeligroEvaluadoDto"][];
            /** @example 72.5 */
            pesoKg?: number;
            /** @example 158 */
            tallaCm?: number;
            /** @example 128 */
            presionSistolica?: number;
            /** @example 82 */
            presionDiastolica?: number;
            /** @example 36.8 */
            temperaturaC?: number;
            /**
             * @description Pulso por minuto.
             * @example 78
             */
            pulso?: number;
            /**
             * @description Respiraciones por minuto.
             * @example 18
             */
            respiraciones?: number;
            /**
             * @description Circunferencia de cintura en centimetros.
             * @example 86
             */
            circunferenciaCinturaCm?: number;
            problemas?: components["schemas"]["ProblemaEvaluadoDto"][];
            medicamentos?: components["schemas"]["MedicamentoIndicadoDto"][];
            /** @description Seccion X. Consejeria brindada. */
            consejeria?: string;
            /** @description A donde se refirio al paciente. */
            referencia?: string;
            /** @description Vacuna aplicada durante la consulta. */
            vacunaAdministrada?: string;
            /** Format: date-time */
            fechaProximaVisita?: string;
            /** @description Resumen del diagnostico, ademas de los del catalogo. */
            diagnostico?: string;
            tratamiento?: string;
            notas?: string;
        };
        FichaCreadaDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            expedienteId: string;
            /** Format: date-time */
            fecha: string;
        };
        SignoPeligroFichaDto: {
            /** Format: uuid */
            signoId: string;
            texto: string;
            presente: boolean;
            detalle: string | null;
        };
        ProblemaFichaRegistradoDto: {
            /** Format: uuid */
            problemaId: string;
            nombre: string;
            presente: boolean;
            /** @description Texto de los signos marcados. */
            signos: string[];
            /** @description Texto de los diagnosticos marcados. */
            diagnosticos: string[];
            otroDiagnostico: string | null;
            conducta: string | null;
        };
        MedicamentoFichaDto: {
            nombre: string;
            dosis: string | null;
            dias: number | null;
        };
        FichaDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            expedienteId: string;
            /** @enum {string|null} */
            tipoFicha: "ADULTO" | "NEONATO" | "NINEZ" | "PRENATAL" | null;
            /** Format: date-time */
            fecha: string;
            /** Format: uuid */
            registradaPor: string;
            digitalizada: boolean;
            motivo: string | null;
            historiaEnfermedad: string | null;
            manejoEstabilizacion: string | null;
            diagnostico: string | null;
            tratamiento: string | null;
            notas: string | null;
            consejeria: string | null;
            referencia: string | null;
            vacunaAdministrada: string | null;
            /**
             * Format: decimal
             * @example 72.50
             */
            pesoKg: string | null;
            /**
             * Format: decimal
             * @example 158.0
             */
            tallaCm: string | null;
            presionSistolica: number | null;
            presionDiastolica: number | null;
            /** Format: decimal */
            temperaturaC: string | null;
            pulso: number | null;
            respiraciones: number | null;
            /** Format: decimal */
            circunferenciaCinturaCm: string | null;
            /**
             * @description Calculado de peso y talla. null si falta alguno de los dos.
             * @example 29.04
             */
            imc: number | null;
            /** Format: date-time */
            fechaProximaVisita: string | null;
            signosPeligro: components["schemas"]["SignoPeligroFichaDto"][];
            problemas: components["schemas"]["ProblemaFichaRegistradoDto"][];
            medicamentos: components["schemas"]["MedicamentoFichaDto"][];
        };
        RespuestaErrorDto: {
            /**
             * @description Codigo estable. El cliente decide que hacer segun este valor, no segun el mensaje.
             * @example VALIDACION
             * @enum {string}
             */
            codigo: "VALIDACION" | "NO_AUTENTICADO" | "SIN_PERMISO" | "NO_ENCONTRADO" | "CONFLICTO" | "DEMASIADAS_PETICIONES" | "ERROR_INTERNO";
            /**
             * @description Mensaje en espanol, apto para mostrarse tal cual al usuario.
             * @example La informacion enviada no es valida.
             */
            mensaje: string;
            /**
             * @description Detalle por campo. Presente sobre todo en errores de validacion.
             * @example [
             *       "dpi debe tener 13 digitos"
             *     ]
             */
            detalles?: string[];
            /**
             * @description Identificador de correlacion. Es lo que se busca en los logs para esta peticion.
             * @example 7f3a1c2e-9b4d-4e21-8a55-0c1d2e3f4a5b
             */
            trazaId: string;
            /** @example /v1/pacientes */
            ruta: string;
            /**
             * Format: date-time
             * @example 2026-08-26T15:04:05.000Z
             */
            fecha: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    SaludController_vivo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludVivoDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    SaludController_listo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaludListoDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description La base de datos no responde. El gateway debe dejar de enviar trafico a esta instancia. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ComunidadesController_listar: {
        parameters: {
            query?: {
                /** @description Con 'true' incluye las comunidades dadas de baja. */
                todas?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComunidadDto"][];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    ComunidadesController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearComunidadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComunidadDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    PacientesController_buscar: {
        parameters: {
            query?: {
                /** @description Busqueda exacta por DPI, resuelta con el indice ciego. */
                dpi?: string;
                /** @description Busqueda por INICIO de apellido o nombre. No busca en medio del texto. */
                nombre?: string;
                comunidadId?: string;
                pagina?: number;
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultados. El listado NO incluye DPI ni telefono. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["PacienteResumenDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    PacientesController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearPacienteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PacienteCreadoDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    PacientesController_obtener: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PacienteDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    PacientesController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarPacienteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PacienteDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    GruposController_listar: {
        parameters: {
            query?: {
                comunidadId?: string;
                /** @description Busca por inicio del codigo del grupo. */
                codigo?: string;
                pagina?: number;
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado paginado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["GrupoFamiliarResumenDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    GruposController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearGrupoDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoFamiliarCreadoDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    GruposController_obtener: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoFamiliarDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    ExpedientesController_porNumero: {
        parameters: {
            query: {
                numero: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpedienteEncontradoDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    AtencionesController_listar: {
        parameters: {
            query?: {
                /** @description Empieza en 1. Por defecto 1. */
                pagina?: number;
                /** @description Por defecto 25. El servidor recorta cualquier valor mayor a 100. */
                tamano?: number;
            };
            header?: never;
            path: {
                expedienteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Atenciones con los campos clinicos ya descifrados. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaDto"] & {
                        datos: components["schemas"]["AtencionDto"][];
                    };
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    AtencionesController_registrar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expedienteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarAtencionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtencionDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    DigitalizacionController_resumen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumenDigitalizacionDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    DigitalizacionController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expedienteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarDigitalizacionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistroDigitalizacionDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    FichasController_catalogo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tipo: "ADULTO" | "NEONATO" | "NINEZ" | "PRENATAL";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogoFichaDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    FichasController_registrar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expedienteId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearFichaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FichaCreadaDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
    FichasController_obtener: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FichaDto"];
                };
            };
            /** @description La informacion enviada no es valida. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Falta el token, expiro o no es valido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El rol de la cuenta no tiene permiso sobre este recurso. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description El recurso solicitado no existe. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
            /** @description Error inesperado. El mensaje real queda en los logs, no se expone. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaErrorDto"];
                };
            };
        };
    };
}
